# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LayoutTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for LayoutTest
  pod 'LayoutTestBase'
  
  target 'LayoutTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'LayoutTest'
  end
end
